name: Go

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Dependency
        run: sudo apt-get install libasound2-dev

      - name: Test
        run: go test ./...
